name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt python-dotenv

      - name: Syntax check
        shell: bash
        run: |
          git ls-files '*.py' | xargs -n1 python -m py_compile

      - name: Smoke test import
        shell: bash
        run: |
          # Ensure backend package imports
          python -c "import sys; sys.path.insert(0, 'backend'); import app; print('import ok')"
